version: '3'
services:
  cypress:
    image: cypress
    build: ./cypress
    container_name: huldhub_cypress
    ports:
      - 7777:7777
    environment:
      - CYPRESS_baseUrl=http://react-app:80
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        rm -f cypress/reports/mocha/*.json
        npx cypress run
        npx mochawesome-merge "cypress/reports/mocha/*.json" > cypress/mochawesome.json
        npx marge cypress/mochawesome.json -o cypress/mochawesome-report	
    volumes:
      - ./cypress/cypress:/app/cypress
      - ./cypress/cypress.json:/app/cypress.json

networks:
  default:
    external: true
    name: huldhub_network