version: '3'
services:
  react-app:
    image: node/huldhub_react
    container_name: huldhub_frontend
    build:
      context:  ./
    restart: always

networks:
  default:
    external: true
    name: huldhub_network